language: java
cache:
directories:
- $HOME/.m2
jdk:
- oraclejdk8
script:
- mvn clean package
sudo: required
services:
- docker
script:
- docker login -u steelrogue -p ODYIpb9jbGk8K0NJyTaH
- mvn clean package docker:build
- docker push tgielis/gs-scheduling-tasks:latest
